package com.flowguard.service;

import io.quarkus.mailer.Mail;
import io.quarkus.mailer.Mailer;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

/**
 * Data breach notification service — RGPD Art. 33 & 34.
 *
 * <p><b>Obligations légales :</b>
 * <ul>
 *   <li>Art. 33 RGPD : Notification à la CNIL dans les <b>72 heures</b> suivant la découverte
 *       d'une violation à risque (probabilité ou gravité non négligeable).
 *   <li>Art. 34 RGPD : Notification aux personnes concernées <b>sans délai</b> si la violation
 *       est susceptible d'engendrer un risque élevé pour leurs droits et libertés.
 *   <li>Art. 33.5 RGPD : Toutes les violations (y compris celles non notifiées) doivent être
 *       <b>documentées</b> dans le registre interne.
 * </ul>
 *
 * <p><b>Workflow :</b>
 * <ol>
 *   <li>Incident détecté → appelas {@link #reportBreach}
 *   <li>Service évalue la gravité et crée une entrée dans le registre interne
 *   <li>Si risque ≥ MEDIUM → email automatique au DPO + alerte Slack/PagerDuty
 *   <li>Si risque ≥ HIGH → prépare le brouillon de notification CNIL (72h)
 *   <li>DPO examine et soumet manuellement via <a href="https://notifications.cnil.fr">portail CNIL</a>
 *   <li>Si risque = CRITICAL → notification aux personnes concernées (Art. 34)
 * </ol>
 */
@ApplicationScoped
public class DataBreachService {

    private static final Logger LOG = Logger.getLogger(DataBreachService.class);

    /** CNIL breach notification portal */
    private static final String CNIL_PORTAL_URL = "https://notifications.cnil.fr/notifications/index";

    @ConfigProperty(name = "flowguard.compliance.officer-email", defaultValue = "compliance@flowguard.fr")
    String complianceOfficerEmail;

    @ConfigProperty(name = "flowguard.dpo.email", defaultValue = "dpo@flowguard.fr")
    String dpoEmail;

    @Inject
    Mailer mailer;

    /**
     * Report a potential data breach.
     *
     * @param incidentId     unique ID for this incident (generated by caller or monitoring system)
     * @param description    factual description of what happened
     * @param severity       estimated severity
     * @param affectedUsers  list of affected user IDs (may be empty if scope unknown)
     * @param dataCategories categories of data potentially compromised
     * @param discoveredAt   when the breach was first discovered
     */
    public void reportBreach(
            UUID incidentId,
            String description,
            BreachSeverity severity,
            List<UUID> affectedUsers,
            List<String> dataCategories,
            Instant discoveredAt
    ) {
        LOG.errorf("DATA BREACH REPORTED: incidentId=%s severity=%s affectedUsers=%d discoveredAt=%s",
                incidentId, severity, affectedUsers.size(), discoveredAt);

        // Always log immediately (Art. 33.5 documentation obligation)
        logToInternalRegister(incidentId, description, severity, affectedUsers, dataCategories, discoveredAt);

        // Notify DPO + compliance immediately for all breaches
        notifyDpo(incidentId, description, severity, affectedUsers, dataCategories, discoveredAt);

        // For HIGH and CRITICAL: prepare CNIL notification draft
        if (severity == BreachSeverity.HIGH || severity == BreachSeverity.CRITICAL) {
            sendCnilNotificationDraft(incidentId, description,
                    affectedUsers, dataCategories, discoveredAt);
        }

        // For CRITICAL: notify affected users (Art. 34 RGPD — high risk to individuals)
        if (severity == BreachSeverity.CRITICAL && !affectedUsers.isEmpty()) {
            notifyAffectedUsers(incidentId, dataCategories);
        }
    }

    // ── Severity assessment helper ────────────────────────────────────────────

    /**
     * Assess breach severity based on data categories and scope.
     * Based on ENISA/CNIL risk matrix.
     */
    public BreachSeverity assessSeverity(List<String> dataCategories, int affectedCount) {
        boolean hasSensitive = dataCategories.stream().anyMatch(c ->
                c.contains("password") || c.contains("financial") || c.contains("health")
                || c.contains("biometric") || c.contains("government_id")
                || c.contains("bank_account") || c.contains("credit_card"));

        boolean hasPersonal = dataCategories.stream().anyMatch(c ->
                c.contains("email") || c.contains("name") || c.contains("phone")
                || c.contains("address") || c.contains("transactions"));

        if (hasSensitive && affectedCount > 100) return BreachSeverity.CRITICAL;
        if (hasSensitive && affectedCount > 0)  return BreachSeverity.HIGH;
        if (hasPersonal && affectedCount > 1000) return BreachSeverity.HIGH;
        if (hasPersonal && affectedCount > 0)   return BreachSeverity.MEDIUM;
        return BreachSeverity.LOW;
    }

    // ── Private ───────────────────────────────────────────────────────────────

    private void logToInternalRegister(
            UUID incidentId, String description, BreachSeverity severity,
            List<UUID> affectedUsers, List<String> dataCategories, Instant discoveredAt
    ) {
        // In production, write to a dedicated breach_incidents table or append to an
        // immutable audit log. For now we log at ERROR level to ensure it's captured
        // by the centralized log aggregation (Grafana/Loki or equivalent).
        LOG.errorf("""
            [BREACH-REGISTER] id=%s severity=%s discoveredAt=%s affectedCount=%d \
            categories=%s description=%s""",
                incidentId, severity, discoveredAt, affectedUsers.size(),
                String.join(",", dataCategories), description);
    }

    private void notifyDpo(
            UUID incidentId, String description, BreachSeverity severity,
            List<UUID> affectedUsers, List<String> dataCategories, Instant discoveredAt
    ) {
        try {
            String subject = String.format("[VIOLATION DE DONNÉES — %s] Incident %s", severity, incidentId);
            String html = buildDpoEmailBody(incidentId, description, severity,
                    affectedUsers, dataCategories, discoveredAt);
            mailer.send(Mail.withHtml(dpoEmail, subject, html));
            mailer.send(Mail.withHtml(complianceOfficerEmail, subject, html));
            LOG.infof("DPO notified for breach %s", incidentId);
        } catch (Exception e) {
            // Email failure must NOT prevent breach logging
            LOG.errorf("CRITICAL: Failed to send DPO breach notification: %s", e.getMessage());
        }
    }

    private void sendCnilNotificationDraft(
            UUID incidentId, String description,
            List<UUID> affectedUsers, List<String> dataCategories, Instant discoveredAt
    ) {
        try {
            String subject = String.format("[ACTION REQUISE 72H] Brouillon notification CNIL — Incident %s", incidentId);
            String html = buildCnilDraftBody(description,
                    affectedUsers, dataCategories, discoveredAt);
            mailer.send(Mail.withHtml(dpoEmail, subject, html));
            LOG.warnf("CNIL notification draft sent for breach %s (72h deadline from %s)", incidentId, discoveredAt);
        } catch (Exception e) {
            LOG.errorf("Failed to send CNIL draft email for breach %s: %s", incidentId, e.getMessage());
        }
    }

    private void notifyAffectedUsers(UUID incidentId, List<String> dataCategories) {
        // Art. 34 notification — requires fetching affected user emails from DB.
        // Implementation: lookup via AgroalDataSource or UserRepository (injected in caller).
        // This stub logs the obligation — production implementation requires UserRepository injection.
        LOG.errorf("[ART-34] CRITICAL breach %s — affected users must be notified WITHOUT DELAY. " +
                "Compromised categories: %s. Implement per-user email dispatch.", incidentId,
                String.join(", ", dataCategories));
    }

    private String buildDpoEmailBody(
            UUID incidentId, String description, BreachSeverity severity,
            List<UUID> affectedUsers, List<String> dataCategories, Instant discoveredAt
    ) {
        String deadline72h = DateTimeFormatter.ISO_INSTANT.format(discoveredAt.plusSeconds(72L * 3600));
        return """
            <html><body style="font-family:sans-serif;color:#333">
            <h2 style="color:#c0392b">🔴 VIOLATION DE DONNÉES PERSONNELLES — Art. 33 RGPD</h2>
            <table border="0" cellpadding="8">
              <tr><td><b>Incident ID</b></td><td>%s</td></tr>
              <tr><td><b>Sévérité</b></td><td style="color:%s"><b>%s</b></td></tr>
              <tr><td><b>Découvert le</b></td><td>%s (UTC)</td></tr>
              <tr><td><b>Deadline CNIL (72h)</b></td><td style="color:#e74c3c"><b>%s (UTC)</b></td></tr>
              <tr><td><b>Personnes affectées</b></td><td>%d</td></tr>
              <tr><td><b>Catégories de données</b></td><td>%s</td></tr>
            </table>
            <h3>Description de l'incident</h3>
            <p style="background:#fff3cd;padding:12px;border-left:4px solid #e74c3c">%s</p>
            <hr>
            <h3>Actions à mener</h3>
            <ol>
              <li>✅ Incident enregistré dans le registre interne (Art. 33.5)</li>
              <li>⚠️ Notifier la CNIL via <a href="%s">%s</a> <b>avant le %s</b></li>
              %s
            </ol>
            <p style="color:#999;font-size:11px">FlowGuard — Data Breach Notification System</p>
            </body></html>
            """.formatted(
                incidentId,
                severity == BreachSeverity.CRITICAL ? "#c0392b" : "#e67e22", severity,
                discoveredAt,
                deadline72h,
                affectedUsers.size(),
                String.join(", ", dataCategories),
                description,
                CNIL_PORTAL_URL, CNIL_PORTAL_URL, deadline72h,
                severity == BreachSeverity.CRITICAL
                    ? "<li>🔴 Notifier les personnes concernées SANS DÉLAI (Art. 34 RGPD)</li>"
                    : ""
        );
    }

    private String buildCnilDraftBody(
            String description,
            List<UUID> affectedUsers, List<String> dataCategories, Instant discoveredAt
    ) {
        return """
            <html><body style="font-family:sans-serif;color:#333">
            <h2>Brouillon — Formulaire de Notification CNIL (Art. 33 RGPD)</h2>
            <p>Portail : <a href="%s">%s</a></p>
            <hr>
            <h3>Informations à saisir sur le portail CNIL</h3>
            <table border="1" cellpadding="8" style="border-collapse:collapse">
              <tr><th>Champ CNIL</th><th>Valeur</th></tr>
              <tr><td>Responsable de traitement</td><td>FlowGuard SAS — [SIRET à compléter]</td></tr>
              <tr><td>DPO</td><td>dpo@flowguard.fr</td></tr>
              <tr><td>Nature de la violation</td><td>%s</td></tr>
              <tr><td>Date de découverte</td><td>%s (UTC)</td></tr>
              <tr><td>Nombre de personnes affectées</td><td>%d (estimation)</td></tr>
              <tr><td>Catégories de données</td><td>%s</td></tr>
              <tr><td>Conséquences probables</td><td>[À évaluer par le DPO]</td></tr>
              <tr><td>Mesures prises</td><td>[À compléter — isolation, patch, réinitialisation passwords, etc.]</td></tr>
            </table>
            <p style="color:#e74c3c"><b>⚠️ Ce formulaire doit être soumis dans les 72h suivant la découverte.</b></p>
            </body></html>
            """.formatted(
                CNIL_PORTAL_URL, CNIL_PORTAL_URL,
                description,
                discoveredAt,
                affectedUsers.size(),
                String.join(", ", dataCategories)
        );
    }

    public enum BreachSeverity {
        /** Likely no/negligible risk — document internally only (Art. 33.5) */
        LOW,
        /** Some risk — notify DPO, assess 72h CNIL obligation */
        MEDIUM,
        /** Significant risk — CNIL notification required within 72h (Art. 33) */
        HIGH,
        /** High risk to individuals — CNIL + affected users notified (Art. 33 + Art. 34) */
        CRITICAL
    }
}
